### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by milely** [naver/garnet#1]
Thanks for the open source code, may I ask when will the pre-trained model be released?

**Comment by hsl323** [comment]
We planned to release pre-trained models at the end of the ECCV 2022 conference.
ECCV 2022 ended last week. It's a bit late, but we're going to release them in a week.
I'll let you know when they're released.

**Comment by hsl323** [comment]
@milely, We just uploaded the pre-trained weight of GaRNet on Hugging Face.
You can find the link in the Pre-trained models section in our README.md.

Also, we upload the subset information of Synthetic data used in training and testing.

**Comment by milely** [comment]
Thank you very much for your work, I will close this issue.
